CREATE TABLE IF NOT EXISTS month_to_date (
  invoice_id TEXT,
  payer_account_id TEXT,
  linked_account_id TEXT,
  record_type TEXT,
  record_id TEXT,
  product_name TEXT,
  rate_id TEXT,
  subscription_id TEXT,
  pricing_plan_id TEXT,
  usage_type TEXT,
  operation TEXT,
  availability_zone TEXT,
  reserved_instance TEXT,
  item_description TEXT,
  usage_start_date TIMESTAMP,
  usage_end_date TIMESTAMP,
  usage_quantity FLOAT8,
  blended_rate NUMERIC(18,11),
  blended_cost NUMERIC(18,11),
  unblended_rate NUMERIC(18,11),
  unblended_cost NUMERIC(18,11),
  resource_id TEXT,
  cloud TEXT,
  slot TEXT,
  PRIMARY KEY(record_id)
) DISTSTYLE EVEN SORTKEY(usage_start_date);
